#!/usr/bin/env bash
sudo echo "Permissions granted ..."

wget "https://www.dropbox.com/download?plat=lnx.x86_64" -O - | tar xzf - -C ~

sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
sudo add-apt-repository "deb http://linux.dropbox.com/ubuntu $(lsb_release -sc) main"

sudo apt-get update
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
sudo apt-get install dropbox python-gpgme -y

killall nautilus
