#!/usr/bin/env bash
set -e

sudo echo "Permissions granted ..."

bash -c "$(curl https://raw.githubusercontent.com/thecotne/foo/master/scripts/wine)"

wget "https://www.dropbox.com/download?plat=lnx.x86_64" -O - | tar xzf - -C ~

sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
sudo add-apt-repository "deb http://linux.dropbox.com/ubuntu $(lsb_release -sc) main"

sudo apt-get update
sudo apt-get install dropbox python-gpgme -y

nautilus --quit
