#!/usr/bin/env bash

function commit {
    git ll

    local label='Commit Message: '
    local msg="${@}"

    if {type vared} &> /dev/null ; then
        vared -p "$label" msg
    else
        read -e -p "$label" -i "$msg" msg
    fi

    git commit -m "$msg"
}

function take {
  mkdir -p $@ && cd ${@:$#}
}

alias dif="git diff"
alias add="git add --all && git ll"

git config --global core.pager "diff-so-fancy | less --tabs=4 -RF"
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
git config --global alias.ll "status -sb -uall"
git config --global alias.amend '!git commit --amend -m "$(git log -1 HEAD --pretty=format:%s)"'
git config --global alias.undo 'reset --soft HEAD~1'
git config --global alias.discard 'reset --hard'
