#!/usr/bin/env bash

# # # # # # # # # # # # # # # # # # # # # # # #
#       git - the stupid content tracker      #
# # # # # # # # # # # # # # # # # # # # # # # #

function commit {
    git ll

    local label='Commit Message: '
    local msg="${@}"

    if {type vared} &> /dev/null ; then
        vared -p "$label" msg
    else
        read -e -p "$label" -i "$msg" msg
    fi

    git commit -m "$msg"
}

function fix {
    git ll

    commitMessage="${@}"

    git commit -m "fix \"${commitMessage}\""
}

function dif {
    git diff --color | diff-so-fancy | less
}

function githubLatestTag {
    finalUrl=`curl https://github.com/$1/releases/latest -s -L -I -o /dev/null -w '%{url_effective}'`
    echo "${finalUrl##*v}"
}

function gitStatus {
    bash -c "cd '$1'; git-radar --bash"
}

function gitStatusAll {
    for dir in *; do
        if [ -d "$dir"/.git ]; then
            echo $(gitStatus "$dir")
        else
            echo
        fi
    done
}

function lg {
    paste -d ' ' <(CLICOLOR_FORCE=true ls -ld *) <(gitStatusAll)
}


# # # # # # # #  git - aliases  # # # # # # # #

alias git="hub"
alias add="git add --all && git ll"

git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
git config --global alias.ll "status -sb"
git config --global alias.amend '!git commit --amend -m "$(git log -1 HEAD --pretty=format:%s)"'
git config --global alias.undo 'reset --soft HEAD~1'
git config --global alias.discard 'reset --hard'


# # # # # # # # # # # # # # # # # # # # # # # #
#           other - everything else           #
# # # # # # # # # # # # # # # # # # # # # # # #

function ssh-chmod {
    chmod 700 ~/.ssh
    chmod 600 ~/.ssh/*
}

function lls {
    CLICOLOR_FORCE=true ls -ld * | awk '{
        k = 0
        s = 0
        for( i = 0; i <= 8; i++ )
        {
            k += ( ( substr( $1, i+2, 1 ) ~ /[rwxst]/ ) * 2 ^( 8 - i ) )
        }
        j = 4
        for( i = 4; i <= 10; i += 3 )
        {
            s += ( ( substr( $1, i, 1 ) ~ /[stST]/ ) * j )
            j/=2
        }
        if ( k )
        {
            printf( "%0o%0o ", s, k )
        }
        print
    }'
}
