#!/usr/bin/env bash
set -e

function HeidiSQLLatestVersion {
    curl http://www.heidisql.com/download.php \
        | grep -oP 'HeidiSQL_\d+\.\d+_Portable.zip' --color=never \
        | head -n1 \
        | grep -oP '\d+\.\d+' --color=never
}

sudo echo "Permissions granted ..."

bash -c "$(curl https://raw.githubusercontent.com/lucenarenato/foo/master/scripts/wine)"

sudo apt update
sudo apt install icoutils imagemagick -y

version=`HeidiSQLLatestVersion`

sudo wget "http://www.heidisql.com/downloads/releases/HeidiSQL_${version}_Portable.zip" -O HeidiSQL.zip
sudo mkdir -pv /opt/HeidiSQL
sudo unzip -o HeidiSQL.zip -d /opt/HeidiSQL
sudo chmod +x -v /opt/HeidiSQL/heidisql.exe

sudo touch /usr/share/applications/HeidiSQL.desktop

cat <<EOF | sudo tee /usr/share/applications/HeidiSQL.desktop > /dev/null
[Desktop Entry]
Name=HeidiSQL
Exec=wine /opt/HeidiSQL/heidisql.exe
Icon=HeidiSQL
Type=Application
Categories=GTK;GNOME;Utility;
EOF

sudo ln -svf /opt/HeidiSQL/heidisql.exe /bin/HeidiSQL

sudo wrestool -x -n MAINICON /opt/HeidiSQL/heidisql.exe | sudo tee /opt/HeidiSQL/HeidiSQL.ico > /dev/null
sudo convert /opt/HeidiSQL/HeidiSQL.ico\[0\] /usr/share/icons/HeidiSQL.png

sudo rm HeidiSQL.zip -fv
