#!/usr/bin/env bash
set -e

function ttfMscorefontsInstallerFix {
    echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    sudo wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb
    sudo apt install ./ttf-mscorefonts-installer_3.6_all.deb -fy
    sudo rm ttf-mscorefonts-installer_3.6_all.deb -fv
}

function sylfaenFix {
    sudo wget https://gist.github.com/thecotne/33fa67bed95d2eb78e1671be060be2cb/raw/5d88b4c6d45afe7a85e9ce03fc3ae10732890762/Sylfaen.ttf -P /usr/share/fonts/ -O Sylfaen.ttf
}

function HeidiSQLLatestVersion {
    curl http://www.heidisql.com/download.php \
        | grep -oP 'HeidiSQL_\d+\.\d+_Portable.zip' --color=never \
        | head -n1 \
        | grep -oP '\d+\.\d+' --color=never
}

sudo echo "Permissions granted ..."

ttfMscorefontsInstallerFix
sylfaenFix

sudo apt update
sudo apt install wine icoutils imagemagick -y

version=`HeidiSQLLatestVersion`

sudo wget "http://www.heidisql.com/downloads/releases/HeidiSQL_${version}_Portable.zip" -O HeidiSQL.zip
sudo mkdir -pv /opt/HeidiSQL
sudo unzip -o HeidiSQL.zip -d /opt/HeidiSQL
sudo chmod +x -v /opt/HeidiSQL/heidisql.exe

sudo touch /usr/share/applications/HeidiSQL.desktop

cat <<EOF | sudo tee /usr/share/applications/HeidiSQL.desktop > /dev/null
[Desktop Entry]
Name=HeidiSQL
Exec=wine /opt/HeidiSQL/heidisql.exe
Icon=HeidiSQL
Type=Application
Categories=GTK;GNOME;Utility;
EOF

sudo ln -svf /opt/HeidiSQL/heidisql.exe /bin/HeidiSQL

sudo wrestool -x -n MAINICON /opt/HeidiSQL/heidisql.exe | sudo tee /opt/HeidiSQL/HeidiSQL.ico > /dev/null
sudo convert /opt/HeidiSQL/HeidiSQL.ico\[0\] /usr/share/icons/HeidiSQL.png

sudo rm HeidiSQL.zip -fv
