#!/usr/bin/env bash
set -e

function ttfMscorefontsInstallerFix {
    echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
    wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb
    apt install ./ttf-mscorefonts-installer_3.6_all.deb -fy
    rm ttf-mscorefonts-installer_3.6_all.deb -f
}

function sylfaenFix {
    wget https://gist.github.com/thecotne/33fa67bed95d2eb78e1671be060be2cb/raw/5d88b4c6d45afe7a85e9ce03fc3ae10732890762/Sylfaen.ttf -P /usr/share/fonts/
}

function HeidiSQLLatestVersion {
    curl http://www.heidisql.com/download.php \
        | grep -oP 'HeidiSQL_\d+\.\d+_Portable.zip' --color=never \
        | head -n1 \
        | grep -oP '\d+\.\d+' --color=never
}

ttfMscorefontsInstallerFix
sylfaenFix

apt-get update
apt-get install wine icoutils imagemagick -y

version=`HeidiSQLLatestVersion`

wget "http://www.heidisql.com/downloads/releases/HeidiSQL_$version_Portable.zip" -O HeidiSQL.zip
mkdir -p /opt/HeidiSQL
unzip HeidiSQL.zip -d /opt/HeidiSQL
chmod +x /opt/HeidiSQL/heidisql.exe

touch /usr/share/applications/HeidiSQL.desktop

cat <<EOF > /usr/share/applications/HeidiSQL.desktop
[Desktop Entry]
Name=HeidiSQL
Exec=wine /opt/HeidiSQL/heidisql.exe
Icon=HeidiSQL
Type=Application
Categories=GTK;GNOME;Utility;
EOF

ln -s /opt/HeidiSQL/heidisql.exe /bin/HeidiSQL

wrestool -x -n MAINICON /opt/HeidiSQL/heidisql.exe > /opt/HeidiSQL/HeidiSQL.ico
convert /opt/HeidiSQL/HeidiSQL.ico\[0\] /usr/share/icons/HeidiSQL.png

rm HeidiSQL.zip -f
