#!/usr/bin/env bash
set -e

function githubLatestTag {
    finalUrl=`curl https://github.com/$1/releases/latest -s -L -I -o /dev/null -w '%{url_effective}'`
    echo "${finalUrl##*v}"
}

mkdir -p ~/bin

if ! [[ `echo "$PATH" | grep -q $HOME/bin && echo '1'` ]]; then
    echo 'PATH="$HOME/bin:$PATH"' >> ~/.bashrc
    export PATH="$HOME/bin:$PATH"
fi

tag=`githubLatestTag zyedidia/micro`

wget "https://github.com/zyedidia/micro/releases/download/v$tag/micro-$tag-linux64.tar.gz" -O micro.tar.gz

mkdir -p ~/bin

tar -zxvf micro.tar.gz "micro-$tag/micro" --show-transformed --strip-components=1

rm micro.tar.gz -f

mv micro ~/bin/micro -f
