#!/usr/bin/env bash
set -e

function ttfMscorefontsInstallerFix {
    echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
    sudo wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb
    sudo apt install ./ttf-mscorefonts-installer_3.6_all.deb -fy
    sudo rm ttf-mscorefonts-installer_3.6_all.deb -fv
}

function sylfaenFix {
    sudo wget https://gist.github.com/thecotne/33fa67bed95d2eb78e1671be060be2cb/raw/5d88b4c6d45afe7a85e9ce03fc3ae10732890762/Sylfaen.ttf -P /usr/share/fonts/ -O Sylfaen.ttf
}

function WinSCPLatestVersion {
    curl https://winscp.net/eng/download.php \
        | grep -oP 'WinSCP-\d+\.\d\.\d+-Portable\.zip' --color=never \
        | head -n1 \
        | grep -oP '\d+\.\d+\.\d+' --color=never
}

sudo echo "Permissions granted ..."

ttfMscorefontsInstallerFix
sylfaenFix

sudo apt update
sudo apt install wine icoutils imagemagick -y

version=`WinSCPLatestVersion`

sudo wget "http://sourceforge.net/projects/winscp/files/WinSCP/$version/WinSCP-${version}-Portable.zip/download" -O WinSCP.zip
sudo mkdir -pv /opt/WinSCP
sudo unzip -o WinSCP.zip -d /opt/WinSCP
sudo chmod +x -v /opt/WinSCP/WinSCP.exe
sudo chmod +x -v /opt/WinSCP/WinSCP.com

sudo touch /usr/share/applications/WinSCP.desktop

cat <<EOF | sudo tee /usr/share/applications/WinSCP.desktop > /dev/null
[Desktop Entry]
Name=WinSCP
Exec=WinSCP
Icon=WinSCP
Type=Application
Categories=GTK;GNOME;Utility;
EOF

sudo ln -svf /opt/WinSCP/WinSCP.exe /bin/WinSCP

sudo wrestool -x -n MAINICON /opt/WinSCP/WinSCP.exe | sudo tee /opt/WinSCP/WinSCP.ico > /dev/null
sudo convert /opt/WinSCP/WinSCP.ico\[0\] /usr/share/icons/WinSCP.png

sudo rm WinSCP.zip -fv
