#!/usr/bin/env bash

echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections

wget http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.6_all.deb
apt install ./ttf-mscorefonts-installer_3.6_all.deb -fy
rm ttf-mscorefonts-installer_3.6_all.deb -f

wget https://gist.github.com/thecotne/33fa67bed95d2eb78e1671be060be2cb/raw/5d88b4c6d45afe7a85e9ce03fc3ae10732890762/Sylfaen.ttf -P /usr/share/fonts/

apt-get update
apt-get install wine icoutils imagemagick -y

wget http://sourceforge.net/projects/winscp/files/WinSCP/5.9.3/WinSCP-5.9.3-Portable.zip/download -O WinSCP.zip
mkdir -p /opt/WinSCP
unzip WinSCP.zip -d /opt/WinSCP
chmod +x /opt/WinSCP/WinSCP.exe
chmod +x /opt/WinSCP/WinSCP.com

touch /usr/share/applications/WinSCP.desktop

cat <<EOF > /usr/share/applications/WinSCP.desktop
[Desktop Entry]
Name=WinSCP
Exec=WinSCP
Icon=WinSCP
Type=Application
Categories=GTK;GNOME;Utility;
EOF

ln -s /opt/WinSCP/WinSCP.exe /bin/WinSCP

wrestool -x -n MAINICON /opt/WinSCP/WinSCP.exe > /opt/WinSCP/WinSCP.ico
convert /opt/WinSCP/WinSCP.ico\[0\] /usr/share/icons/WinSCP.png

rm WinSCP.zip -f
